"""add book table

Revision ID: 5f0c8f31471f
Revises: 19262534251e
Create Date: 2024-12-04 22:21:15.591086

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f0c8f31471f'
down_revision = '19262534251e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('book_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_uuid', mysql.CHAR(length=36), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('author', sa.String(length=150), nullable=False),
    sa.Column('genre', sa.String(length=150), nullable=False),
    sa.Column('publication_date', sa.DateTime(), nullable=False),
    sa.Column('ISBN', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=150), nullable=False),
    sa.Column('summary', sa.TEXT(), nullable=False),
    sa.Column('cover_image_url', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('book_id'),
    sa.UniqueConstraint('book_uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    # ### end Alembic commands ###
